PADEL_COURT_LENGTH = 20
PADEL_COURT_WIDTH = 10
PADEL_SERVICE_LINE_DISTANCE = 3
#PADEL_SERVICE_BOX_HEIGHT = 4.5
#PADEL_SERVICE_BOX_WIDTH = 5
padle_serviceline= 7

PLAYER_1_HEIGHT_METERS = 1.79
PLAYER_2_HEIGHT_METERS = 1.79
PLAYER_3_HEIGHT_METERS=1.79
PLAYER_4_HEIGHT_METERS=1.79